pvl/abap.tmbundle

Syntaxes/ABAP.tmLanguage
ignore case for ENDCLASS, ENDMETHOD, and ENDFORM
keywords added: RAISING, PRIVATE, CHANGING
=> ignore case, add keywords

Syntaxes/ABAP.tmLanguage
=> Added support for pragma directives

Syntaxes/ABAP.tmLanguage
=> Support for inline data declaration, returning value

Syntaxes/ABAP.tmLanguage
=> Fixed base abap types on lines ending with a comma

Syntaxes/ABAP.tmLanguage
List based on https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abensystem_fields.htm
=> Added support for system fields

Syntaxes/ABAP.tmLanguage
Full list:
table_line, abap_bool, abstract, appending, cast, ending, first, for, occurrence, screen, starting, testing, then, transporting, work, as, by, no
=> Added several new keywords

Syntaxes/ABAP.tmLanguage
=> Fixed highlighting of class modifiers

Syntaxes/ABAP.tmLanguage
=> Added numeric literals

Syntaxes/ABAP.tmLanguage
Fixes all keywords in #43 as well as #32
=> Added keywords, fixed keywords followed by a comma

Syntaxes/ABAP.tmLanguage
=> Fixed class names with namespaces

Syntaxes/ABAP.tmLanguage
#49 except for TEXT-xxx and some others.
=> Added missing keywords

Syntaxes/ABAP.tmLanguage
Forgot about this, it's been in vscode for a while:
https://github.com/larshp/vscode-abap/pull/9
=> Highlighting for builtin functions

Syntaxes/ABAP.tmLanguage
Fixes #52. 
Also corrects the colors for methods and considers interfaces.
=> Added AMDP highlighting

Syntaxes/ABAP.tmLanguage
=> Fixed method, interface, form declarations + minor issues

Syntaxes/ABAP.tmLanguage
```abap
IF x IS INSTANCE OF y.
INCLUDE incl IF FOUND. 
AT SELECTION-SCREEN OUTPUT.
```
=> Add instance, output, found

Syntaxes/ABAP.tmLanguage
This includes only
https://github.com/larshp/vscode-abap/pull/11
=> Sync grammar with vscode-abap

Syntaxes/ABAP.tmLanguage
adds div, mod and the bit operators
=> Extend the list of operators

Syntaxes/ABAP.tmLanguage
*   add sql related keywords - union, distinct, join, inner
*   fix text symbol coloring
*   no longer color the dash in system fields (sy-subrc)
=> Minor update

Syntaxes/ABAP.tmLanguage
```abap
BADI
PRIVILEGED ACCESS
COMPARING
GET/SET PARAMETER
TRANSACTION
PF-STATUS
EXCLUDING
LIST-PROCESSING
MEMORY
CHECKBOX
```
=> Add missing keywords

Syntaxes/ABAP.tmLanguage
Fixes regex for operators and class names
=> Fix regex escaping

Syntaxes/ABAP.tmLanguage
Closes https://github.com/pvl/abap.tmbundle/issues/79
https://regex101.com/r/JZKDIZ/1
=> Fix invalid regex (lookbehind assertion)

Syntaxes/ABAP.tmLanguage
=> Pretty-print grammar

Syntaxes/ABAP.tmLanguage
- Add `for behavior of`
- Add `by kernel module`
- Add `like`, `line of` to type defs
=> Update class, method, type definitions

Syntaxes/ABAP.tmLanguage
Improve highlighting of ABAP SQL statements
=> Add SQL data types and functions

Syntaxes/ABAP.tmLanguage
=> Update keyword list
